### PR TITLE
Task/issue 26/API URL are hardcoded

### LINKED ISSUE #26: API url are hardcoded to localhost:8000
### Describe the bug

title

### How to Reproduce

_No response_

### Expected behavior

This should not be present

### Additional context

_No response_

### Pre-submission checklist

- [x] I have SET the apropriate label
- [x] I have SET the apropriate milestone
- [x] I have UNSET the issue tag

### PR DESCRIPTION
**Pull request by Lilianbazantay**
- closes #26

## Checklist
- [X] I have renamed the first header of the template -_-
- [X] I have tested my modifications
- [ ] I have done the relevant documentation
- [X] I have set the Reviewers & Assignees
- [X] I have set the correct `Labels`
- [X] I have set the `area` project
- [X] I have set `Status` / `Priority` / `Size` / `Start date` / `End date`
- [X] I have set the relevant `Milestone`

### CODE REVIEW

File: front/src/api_url.ts [hunk 1]
```diff
@@ -0,0 +1,2 @@
+export const API_BASE_URL =
+  process.env.NODE_ENV === "production" ? "" : "http://127.0.0.1:8000";
```
Comment (ElectronicIV) [inline front/src/api_url.ts:2]: We'll see later for a better way to implement this

**Review by ElectronicIV — APPROVED** [review]
